### ISSUE TITLE
Got AttributeError when running attack.sage

### ISSUE THREAD

**Issue by ZM-J** [Breaking-SIDH/direct-attack#1]
Hi! Recently I noticed this repo and ran your code `attack.sage`. However, in SageMath 9.6, I got the following error:

```
Generating the public parameters for the attack required 0.35s
----------------------------------------------------------------------
Computing cofactor isogeny for prime factor: q = 5
DEBUG [gen_xpoint_order_q]: Needed to compute an extension of degree k = 2
Traceback (most recent call last):
  File "attack.sage.py", line 160, in <module>
    phi_temp = an_isogeny(E_temp, q)
  File "/xxx/yyy/zzz/direct-attack/attack_aux.py", line 77, in an_isogeny
    kerpoly = kernel_polynomial_from_x(EE, x, q)
  File "/xxx/yyy/zzz/direct-attack/xonly.py", line 249, in kernel_polynomial_from_x
    fs = [minpoly(x)]
  File "/xxx/yyy/zzz/direct-attack/xonly.py", line 247, in minpoly
    return ntl_funs(F2).minpoly_mod(ext(elt).vector(), ext.modulus())
  File "/xxx/yyy/zzz/direct-attack/xonly.py", line 109, in minpoly_mod
    ntl_mod = self.ntlify(mod)
  File "/xxx/yyy/zzz/direct-attack/xonly.py", line 106, in ntlify
    return ntl.ZZ_pEX([ntl.ZZ_pE(c.list(), self.ctx) for c in poly])
  File "/xxx/yyy/zzz/direct-attack/xonly.py", line 106, in <listcomp>
    return ntl.ZZ_pEX([ntl.ZZ_pE(c.list(), self.ctx) for c in poly])
  File "sage/structure/element.pyx", line 494, in sage.structure.element.Element.__getattr__ (build/cythonized/sage/structure/element.c:4831)
  File "sage/structure/element.pyx", line 507, in sage.structure.element.Element.getattr_from_category (build/cythonized/sage/structure/element.c:4943)
  File "sage/cpython/getattr.pyx", line 361, in sage.cpython.getattr.getattr_from_other_class (build/cythonized/sage/cpython/getattr.c:2702)
AttributeError: 'sage.rings.finite_rings.element_pari_ffelt.FiniteFieldElement_pari_ffelt' object has no attribute 'list'
```

Do you know why did I get this error and how should I fix this? I need your help.

BTW, the type of `c` in `poly` in `xonlyl.py` line 106 is:

```
<class 'sage.rings.finite_rings.element_pari_ffelt.FiniteFieldElement_pari_ffelt'>
```

**Comment by ZM-J** [comment]
It seems that the reason of this exception is related to SageMath 9.6. Now I tried using this repo with SageMath 10.x, and it worked then.
